
export interface Company {
  id: number;
  name: string;
  fullName: string;
  createdBy: string;
  // dotyczy: string;
  // bankAccount: string;
  // campaignId: number;
  // created: Date;
  // dbOwnerIds: string;
  // dbOwners: string;
  // deliveryTerms: string;
  // deliveryType: string;
  // detailedType: string;
  // division: string;
  // employees: number;
  // extSymbol: string;
  // fax1: string;
  // field0: string;
  // filed1: string;
  // filed2: string;
  // filed3: string;
  // filed4: string;
  // filed5: string;
  // filed6: string;
  // filed7: string;
  // filed8: string;
  // filed9: string;
  // industry: string;
  // lastModified: Date;
  // lastModifiedBy: string;
  // mainEmail: string;
  // note: string;
  // parent: number;
  // paymentDays: number;
  // paymentTerms: string;
  // person: boolean;
  // phone1: string;
  // phone2: string;
  // priceLevel: number;
  // rating: string;
  // ratingCredit: string;
  // regnum: string;
  // regnumExt: string;
  // salesEmail: string;
  // satisfaction: string;
  // sicCode: string;
  // source: string;
  // status: string;
  // supportEmail: string;
  // territory: string;
  // type: string;
  // wwwAddress: string;
  // yearlyRevenue: number;

}
